version: '3.7'

services:
  delayed_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver/int-development-main_server
    networks:
      - default
      - logs
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1

  cron_job:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver/int-development-main_server
    networks:
      - default
      - public
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      replicas: 0
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.skip-running: "true"
        swarm.cronjob.schedule: 1 1 1 * * *
        traefik.docker.network: public
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 1

  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-mainserver/int-development-main_server
    networks:
      - default
      - logs
      - sva-redis-server
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30


  nginx:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.docker.network: public
        traefik.frontend.rule: Host:server.int-development.smart-village.app

  db:
    networks:
      default:
      adminer:
        aliases:
          - int-development-mainserver

networks:
  adminer:
    external: true
  logs:
    external: true
  public:
    external: true
